// Aqui puedes agregar los datos que necesites para tus pruebas
// al menos debe tener uno que se llame "data"
export const data = [{
  "id": 1,
  "name": "Color TV Game",
  "shortDescription": "Color TV-Game fue la primera consola de videojuegos doméstica de Nintendo y se comercializó exclusivamente en Japón. Esta consola incluía una serie de videojuegos almacenados en su memoria interna ya que aún no existían los cartuchos intercambiables.",
  "description": "Color TV-Game fue la primera consola de videojuegos doméstica de Nintendo y se comercializó exclusivamente en Japón. Esta consola incluía una serie de videojuegos almacenados en su memoria interna ya que aún no existían los cartuchos intercambiables.",
  "imageUrl": "/data/img/colort.png",
  "tipo": "Consola de sobremesa",
  "PrecioDeLanzamiento": "$199 USD",
  "JuegoMásPopular": "Variaciones del Pong",
  "DuraciónEnElMercado": "6 años",
  "generation": "Primera Generación",
  "numberGeneration": 1,
  "numberType": 11
},
{
  "id": 2,
  "name": "Game & Watch",
  "shortDescription": "La serie Game & Watch (conocidas en Alemania como tricOtronic y popularmente en España como «maquinitas») es una línea de 59 consolas portátiles de videojuegos fabricadas por Nintendo y creadas por Gunpei Yokoi de 1980 a 1991. Cada una de ellas poseían un único juego de pantalla LCD y tenían además reloj y alarma.",
  "description": "La serie Game & Watch (conocidas en Alemania como tricOtronic y popularmente en España como «maquinitas») es una línea de 59 consolas portátiles de videojuegos fabricadas por Nintendo y creadas por Gunpei Yokoi de 1980 a 1991. Cada una de ellas poseían un único juego de pantalla LCD y tenían además reloj y alarma.",
  "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/1/15/Game_%26_Watch.png",
  "tipo": "Consola portátil",
  "PrecioDeLanzamiento": "$40 USD",
  "JuegoMásPopular": "Epoch Man",
  "DuraciónEnElMercado": "15 años",
  "generation": "Segunda Generación",
  "numberGeneration": 2,
  "numberType": 7
},
{
  "id": 3,
  "name": "Nintendo (NES)",
  "shortDescription": "Está considerada como la videoconsola más exitosa de su época y contribuyó a revitalizar de forma significativa la industria estadounidense de los videojuegos, la cual había sufrido previamente una debacle financiera en 1983, además de establecer el nivel estándar para consolas posteriores en aspectos primordiales.",
  "description": "Está considerada como la videoconsola más exitosa de su época y contribuyó a revitalizar de forma significativa la industria estadounidense de los videojuegos, la cual había sufrido previamente una debacle financiera en 1983, además de establecer el nivel estándar para consolas posteriores en aspectos primordiales.",
  "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/NES-Console-Set.png/1024px-NES-Console-Set.png",
  "tipo": "Consola de sobremesa",
  "PrecioDeLanzamiento": "$179.99 USD",
  "DuraciónEnElMercado": "12 años",
  "JuegoMásPopular": "Super Mario Bros",
  "generation": "Tercera Generación",
  "numberGeneration": 3,
  "numberType": 11
},
{
  "id": 4,
  "name": "Family Computer (Famicom)",
  "shortDescription": "Antes que la NES fue la Famicom de Nintendo. La consola más importante de todos los tiempos, la consola de videojuegos por excelencia de Nintendo, una máquina de 8 Bits que copó y revolucionó el mercado de los videojuegos, conquistando posteriormente gracias a la calidad de sus videojuegos, todo el globo terráqueo.",
  "description": "Antes que la NES fue la Famicom de Nintendo. La consola más importante de todos los tiempos, la consola de videojuegos por excelencia de Nintendo, una máquina de 8 Bits que copó y revolucionó el mercado de los videojuegos, conquistando posteriormente gracias a la calidad de sus videojuegos, todo el globo terráqueo.",
  "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Nintendo-Famicom-Console-Set-FL.png/1280px-Nintendo-Famicom-Console-Set-FL.png",
  "tipo": "Consola de sobremesa",
  "PrecioDeLanzamiento": "$99 USD",
  "JuegoMásPopular": "Super Mario Bros",
  "DuraciónEnElMercado": "20 años",
  "generation": "Tercera Generación",
  "numberGeneration": 3,
  "numberType": 11
},
{
  "id": 5,
  "name": "Game Boy",
  "shortDescription": "La Game Boy es una videoconsola portátil de 8 bits. Salió a la venta por primera vez en Japón el 21 de abril de 1989, en Norteamérica más tarde ese mismo año y en Europa a finales de 1990.Es la segunda consola portátil de Nintendo y combina características de la consola portátil Game & Watch y de la consola doméstica NES.",
  "description": "La Game Boy es una videoconsola portátil de 8 bits. Salió a la venta por primera vez en Japón el 21 de abril de 1989, en Norteamérica más tarde ese mismo año y en Europa a finales de 1990.Es la segunda consola portátil de Nintendo y combina características de la consola portátil Game & Watch y de la consola doméstica NES.",
  "imageUrl": "/data/img/Game-Boy.png",
  "tipo": "Consola portátil",
  "PrecioDeLanzamiento": "$199 USD",
  "JuegoMásPopular": "Tetris",
  "DuraciónEnElMercado": "9 años",
  "generation": "Cuarta Generación",
  "numberGeneration": 4,
  "numberType": 7
},
{
  "id": 6,
  "name": "Super Nintendo (SNES)",
  "shortDescription": "Super Nintendo Entertainment System, también conocida como la Super NES o la Super Family Computer (abreviada como SNES, Super NES o Super Famicom), es una consola de videojuegos de 16 bits desarrollada por Nintendo que fue lanzada en 1990 en Japón y Corea del Sur, en 1991 en Norteamérica, en 1992 en Europa y Australia (1992) y en América del Sur (1993).",
  "description": "Super Nintendo Entertainment System, también conocida como la Super NES o la Super Family Computer (abreviada como SNES, Super NES o Super Famicom), es una consola de videojuegos de 16 bits desarrollada por Nintendo que fue lanzada en 1990 en Japón y Corea del Sur, en 1991 en Norteamérica, en 1992 en Europa y Australia (1992) y en América del Sur (1993).",
  "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/SNES-Mod1-Console-Set.png/1024px-SNES-Mod1-Console-Set.png",
  "tipo": "Consola de sobremesa",
  "PrecioDeLanzamiento": "$199 USD",
  "JuegoMásPopular": "Super Mario World",
  "DuraciónEnElMercado": "10 años",
  "generation": "Cuarta Generación",
  "numberGeneration": 4,
  "numberType": 11
},
{
  "id": 7,
  "name": "Nintendo 64",
  "shortDescription": "Nintendo 64, comúnmente abreviada como N64, es la tercera videoconsola de sobremesa de Nintendo. Fue lanzada por primera vez el 23 de junio de 1996 en Japón, el 29 de septiembre de 1996 en Norteamérica, el 1 de marzo de 1997 en Europa y Australia, y el 1 de septiembre de 1997 en Francia.",
  "description": "Nintendo 64, comúnmente abreviada como N64, es la tercera videoconsola de sobremesa de Nintendo. Fue lanzada por primera vez el 23 de junio de 1996 en Japón, el 29 de septiembre de 1996 en Norteamérica, el 1 de marzo de 1997 en Europa y Australia, y el 1 de septiembre de 1997 en Francia.",
  "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/N64-Console-Set.png/1024px-N64-Console-Set.png",
  "tipo": "Consola de sobremesa",
  "PrecioDeLanzamiento": "$199 USD",
  "JuegoMásPopular": "Super Mario 64",
  "DuraciónEnElMercado": "6 años",
  "generation": "Quinta Generación",
  "numberGeneration": 5,
  "numberType": 11
},
{
  "id": 8,
  "name": "Virtual Boy",
  "shortDescription": "Virtual Boy es una consola de videojuegos portátil de mesa desarrollada y fabricada por Nintendo. Fue comercializada como el primer sistema de realidad virtual portátil. La consola consiste en un visor montado en un trípode que proyecta imágenes monocromáticas rojas y en tres dimensiones.",
  "description": "Virtual Boy es una consola de videojuegos portátil de mesa desarrollada y fabricada por Nintendo. Fue comercializada como el primer sistema de realidad virtual portátil. La consola consiste en un visor montado en un trípode que proyecta imágenes monocromáticas rojas y en tres dimensiones.",
  "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/8/88/Nintendo-Virtual-Boy-Set.png",
  "tipo": "Consola de sobremesa",
  "PrecioDeLanzamiento": "$179.99 USD",
  "JuegoMásPopular": "Mario's Tennis",
  "DuraciónEnElMercado": "1 año",
  "generation": "Quinta Generación",
  "numberGeneration": 5,
  "numberType": 11
},
{
  "id": 9,
  "name": "Game Boy Color",
  "shortDescription": "Game Boy Color es una consola portátil lanzada por Nintendo en octubre de 1998 en Japón y Norteamérica y en noviembre de 1998 en Europa. Fue creada y manufacturada por la compañía Nintendo y es la sucesora de la Game Boy.",
  "description": "Game Boy Color es una consola portátil lanzada por Nintendo en octubre de 1998 en Japón y Norteamérica y en noviembre de 1998 en Europa. Fue creada y manufacturada por la compañía Nintendo y es la sucesora de la Game Boy.",
  "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Game-Boy-Color-Purple-FL.png/800px-Game-Boy-Color-Purple-FL.png",
  "tipo": "Consola portátil",
  "PrecioDeLanzamiento": "$69.95 USD",
  "JuegoMásPopular": "Pokémon Rojo y Azul",
  "DuraciónEnElMercado": "9 años",
  "generation": "Cuarta Generación",
  "numberGeneration": 4,
  "numberType": 7
},
{
  "id": 10,
  "name": "Game Boy Advance",
  "shortDescription": "La Game Boy Advance es una videoconsola portátil de la empresa Nintendo, fue desarrollada para suceder a la Game Boy Color, y compitió en la sexta generación de videoconsolas junto con la Neo Geo Pocket Color de SNK y la WonderSwan de Bandai (aunque esta última no tuvo mucho éxito).",
  "description": "La Game Boy Advance es una videoconsola portátil de la empresa Nintendo, fue desarrollada para suceder a la Game Boy Color, y compitió en la sexta generación de videoconsolas junto con la Neo Geo Pocket Color de SNK y la WonderSwan de Bandai (aunque esta última no tuvo mucho éxito).",
  "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Game-Boy-Advance-FL.png/800px-Game-Boy-Advance-FL.png",
  "tipo": "Consola portátil",
  "PrecioDeLanzamiento": "$99.99 USD",
  "JuegoMásPopular": "Pokémon Rubí y Zafiro",
  "DuraciónEnElMercado": "5 años",
  "generation": "Sexta Generación",
  "numberGeneration": 6,
  "numberType": 7
},
{
  "id": 11,
  "name": "Nintendo GameCube",
  "shortDescription": "Nintendo GameCube es una consola de videojuegos lanzada por Nintendo en Japón y América del Norte en 2001 y en Europa y Australia en 2002. La sexta generación de consolas de videojuegos, el sucesor de la Nintendo 64.",
  "description": "Nintendo GameCube es una consola de videojuegos lanzada por Nintendo en Japón y América del Norte en 2001 y en Europa y Australia en 2002. La sexta generación de consolas de videojuegos, el sucesor de la Nintendo 64.",
  "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/GameCube-Set.jpg/800px-GameCube-Set.jpg",
  "tipo": "Consola de sobremesa",
  "PrecioDeLanzamiento": "$199.99 USD",
  "JuegoMásPopular": "Super Smash Bros. Melee",
  "DuraciónEnElMercado": "6 años",
  "generation": "Sexta Generación",
  "numberGeneration": 6,
  "numberType": 11
},
{
  "id": 12,
  "name": "Nintendo DS",
  "shortDescription": "Nintendo DS es una consola de videojuegos portátil desarrollada y fabricada por Nintendo. Fue lanzada en 2004 en Canadá y Estados Unidos y en 2005 en Europa, Australia y China. Es la primera consola de la serie Nintendo DS y es conocida por su capacidad para mostrar gráficos en 3D.",
  "description": "Nintendo DS es una consola de videojuegos portátil desarrollada y fabricada por Nintendo. Fue lanzada en 2004 en Canadá y Estados Unidos y en 2005 en Europa, Australia y China. Es la primera consola de la serie Nintendo DS y es conocida por su capacidad para mostrar gráficos en 3D.",
  "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Nintendo-DS-Blue.jpg/800px-Nintendo-DS-Blue.jpg",
  "tipo": "Consola portátil",
  "PrecioDeLanzamiento": "$149.99 USD",
  "JuegoMásPopular": "New Super Mario Bros.",
  "DuraciónEnElMercado": "8 años",
  "generation": "Séptima Generación",
  "numberGeneration": 7,
  "numberType": 7
},
{
  "id": 13,
  "name": "Wii",
  "shortDescription": "La Wii es una consola de videojuegos doméstica lanzada por Nintendo el 19 de noviembre de 2006. Como sucesora de la Nintendo GameCube, es parte de la séptima generación de consolas y compite con Sony PlayStation 3 y Microsoft Xbox 360.",
  "description": "La Wii es una consola de videojuegos doméstica lanzada por Nintendo el 19 de noviembre de 2006. Como sucesora de la Nintendo GameCube, es parte de la séptima generación de consolas y compite con Sony PlayStation 3 y Microsoft Xbox 360.",
  "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Wii-Console-Blue.png/800px-Wii-Console-Blue.png",
  "tipo": "Consola de sobremesa",
  "PrecioDeLanzamiento": "$249.99 USD",
  "JuegoMásPopular": "Wii Sports",
  "DuraciónEnElMercado": "7 años",
  "generation": "Séptima Generación",
  "numberGeneration": 7,
  "numberType": 11
},
{
  "id": 14,
  "name": "Nintendo DS Lite",
  "description": "La Nintendo DS Lite es un 21% más ligera que el modelo original. La posición de los botones ha sido cambiada ligeramente, como el botón ON/OFF que ha sido cambiado, de estar encima de la cruceta de control y ser un botón, a estar en el lado derecho de la consola y ser movido con el dedo.",
  "shortDescription": "La Nintendo DS Lite es un 21% más ligera que el modelo original. La posición de los botones ha sido cambiada ligeramente, como el botón ON/OFF que ha sido cambiado, de estar encima de la cruceta de control y ser un botón, a estar en el lado derecho de la consola y ser movido con el dedo.",
  "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Nintendo-DS-Lite-w-stylus.png/800px-Nintendo-DS-Lite-w-stylus.png",
  "tipo": "Consola portátil doble pantalla",
  "PrecioDeLanzamiento": "$129.99 USD",
  "JuegoMásPopular": "Nintendogs",
  "DuraciónEnElMercado": "2 años",
  "generation": "Sexta Generacion",
  "numberGeneration": 6,
  "numberType": 4
},
{
  "id": 15,
  "name": "Wii",
  "description": "La característica más distintiva de la consola fue su mando inalámbrico, el Wii Remote, el cual se usaba como un dispositivo de mano con el que se podía apuntar, además de que detectaba movimientos en un plano tridimensional. Otra de sus peculiaridades era el servicio WiiConnect24, que permitía recibir mensajes y actualizaciones a través de Internet en modo de espera.",
  "shortDescription": "La característica más distintiva de la consola fue su mando inalámbrico, el Wii Remote, el cual se usaba como un dispositivo de mano con el que se podía apuntar, además de que detectaba movimientos en un plano tridimensional. Otra de sus peculiaridades era el servicio WiiConnect24, que permitía recibir mensajes y actualizaciones a través de Internet en modo de espera.",
  "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Wii_console.png/800px-Wii_console.png",
  "tipo": "Consola de sobremesa",
  "PrecioDeLanzamiento": "$249.99 USD",
  "JuegoMásPopular": "Wii Sports",
  "DuraciónEnElMercado": "7 años",
  "generation": "Septima Generacion",
  "numberGeneration": 7,
  "numberType": 11
},
{
  "id": 16,
  "name": "Nintendo DSi XL",
  "description": "Nintendo DSi XL incluye todas las funciones de la videoconsola portátil Nintendo DSi: dos cámaras de fotos, editor de imágenes y sonido, grabadora y reproductor de sonido, la posibilidad de descargar programas directamente a la consola desde la aplicación Tienda Nintendo DSi.",
  "shortDescription": "Nintendo DSi XL incluye todas las funciones de la videoconsola portátil Nintendo DSi: dos cámaras de fotos, editor de imágenes y sonido, grabadora y reproductor de sonido, la posibilidad de descargar programas directamente a la consola desde la aplicación Tienda Nintendo DSi.",
  "imageUrl": "/data/img/Nintendo-DSi-XL.png",
  "tipo": "Portátil doble pantalla",
  "PrecioDeLanzamiento": "$189.99 USD",
  "JuegoMásPopular": "Super Smash Bros. Melee",
  "DuraciónEnElMercado": "2 años",
  "generation": "Séptima Generacion",
  "numberGeneration": 7,
  "numberType": 4
},
{
  "id": 17,
  "name": "Nintendo 3DS ",
  "description": "Nintendo 3DS es una videoconsola portátil descontinuada de la multinacional de origen japonés, Nintendo, para videojuegos y multimedia, cuya atracción principal es poder mostrar gráficos en 3D sin necesidad de gafas especiales, gracias a la autoestereoscopia.La consola es retrocompatible con la Nintendo DS y con el software de DSiWare.",
  "shortDescription": "Nintendo 3DS es una videoconsola portátil descontinuada de la multinacional de origen japonés, Nintendo, para videojuegos y multimedia, cuya atracción principal es poder mostrar gráficos en 3D sin necesidad de gafas especiales, gracias a la autoestereoscopia.La consola es retrocompatible con la Nintendo DS y con el software de DSiWare.",
  "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Nintendo-3DS-AquaOpen.png/800px-Nintendo-3DS-AquaOpen.png",
  "tipo": "Portátil doble pantalla 3D.",
  "PrecioDeLanzamiento": "$249.99 USD",
  "JuegoMásPopular": "  Mario Kart 7",
  "DuraciónEnElMercado": "2 años",
  "generation": "Octava Generacion",
  "numberGeneration": 8,
  "numberType": 4
},
{
  "id": 18,
  "name": "Wii Mini",
  "description": "Wii Mini significa menos tamaño pero también la reducción de funcionalidades. La retrocompatibilidad con los juegos de Gamecube se queda fuera así como las opciones online. Un hecho curioso, si bien es cierto que el fuerte de Wii no era el juego multijugador, si no el compartir esos momentos con los amigos. ",
  "shortDescription": "Wii Mini significa menos tamaño pero también la reducción de funcionalidades. La retrocompatibilidad con los juegos de Gamecube se queda fuera así como las opciones online. Un hecho curioso, si bien es cierto que el fuerte de Wii no era el juego multijugador, si no el compartir esos momentos con los amigos. ",
  "imageUrl": "/data/img/wii_mini-removebg-previe.png",
  "tipo": "Consola de sobremesa",
  "PrecioDeLanzamiento": " $99.99 USD",
  "JuegoMásPopular": " Igual al Wii",
  "DuraciónEnElMercado": " 5 años",
  "generation": "Séptima Generacion",
  "numberGeneration": 7,
  "numberType": 11
},
{
  "id": 19,
  "name": "Wii U",
  "description": "Wii U es la primera consola de Nintendo en producir gráficos en alta definición hasta una resolución de 1080p. Incluyó un nuevo mando que incorporó una pantalla táctil que recibía señal en calidad 480p de la consola, lo que permitió seguir jugando incluso cuando el televisor estaba apagado.",
  "shortDescription": "Wii U es la primera consola de Nintendo en producir gráficos en alta definición hasta una resolución de 1080p. Incluyó un nuevo mando que incorporó una pantalla táctil que recibía señal en calidad 480p de la consola, lo que permitió seguir jugando incluso cuando el televisor estaba apagado.",
  "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Wii_U_Console_and_Gamepad.png/1280px-Wii_U_Console_and_Gamepad.png",
  "tipo": "Consola sobremesa GamePad",
  "PrecioDeLanzamiento": "$349.99 USD",
  "JuegoMásPopular": "Mario Kart 8",
  "DuraciónEnElMercado": "5 años",
  "generation": "Octava Generacion",
  "numberGeneration": 8,
  "numberType": 11
},
{
  "id": 20,
  "name": "New Nintendo 3DS",
  "description": "La New Nintendo 3DS presenta varios cambios respecto a la Nintendo 3DS original y a la Nintendo 3DS XL. Las adiciones más notables son la inclusión de una segunda palanca de control analógico en el lado derecho de la consola, conocida como el C-Stick, y los nuevos botones traseros ZL y ZR.",
  "shortDescription": "La New Nintendo 3DS presenta varios cambios respecto a la Nintendo 3DS original y a la Nintendo 3DS XL. Las adiciones más notables son la inclusión de una segunda palanca de control analógico en el lado derecho de la consola, conocida como el C-Stick, y los nuevos botones traseros ZL y ZR.",
  "imageUrl": "/data/img/new_nintendo_3ds-.png",
  "tipo": "Consola portátil",
  "PrecioDeLanzamiento": "$179.99 USD",
  "JuegoMásPopular": "Super Smash Bros.",
  "DuraciónEnElMercado": "2 años",
  "generation": "Octava Generacion",
  "numberGeneration": 8,
  "numberType": 7
},
{
  "id": 21,
  "name": "Nintendo Classic Mini: Super NES",
  "description": "es una réplica en miniatura de la Super Nintendo Entertainment System que se lanzó originalmente en 1991 en Europa. La consola presenta 21 juegos precargados e incluye dos mandos con cable para poder jugar en multijugador.",
  "shortDescription": "es una réplica en miniatura de la Super Nintendo Entertainment System que se lanzó originalmente en 1991 en Europa. La consola presenta 21 juegos precargados e incluye dos mandos con cable para poder jugar en multijugador.",
  "imageUrl": "/data/img/NES-Mini.png",
  "tipo": "Consola de sobremesa",
  "PrecioDeLanzamiento": "$79.99 USD",
  "JuegoMásPopular": "Super Mario World",
  "DuraciónEnElMercado": "1 año",
  "generation": "Novena Generacion",
  "numberGeneration": 9,
  "numberType": 11
},
{
  "id": 22,
  "name": "Game Boy Micro",
  "description": "Es una consola de videojuegos portátil desarrollada y fabricada por Nintendo. Se lanzó en septiembre de 2005 en Japón y en octubre de ese mismo año en América del Norte y Europa. Es la última consola de la línea Game Boy.",
  "shortDescription": "Es una consola de videojuegos portátil desarrollada y fabricada por Nintendo. Se lanzó en septiembre de 2005 en Japón y en octubre de ese mismo año en América del Norte y Europa. Es la última consola de la línea Game Boy.",
  "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Game-Boy-Micro-Blue.png/800px-Game-Boy-Micro-Blue.png",
  "tipo": "Consola portátil",
  "PrecioDeLanzamiento": "$99.99 USD",
  "JuegoMásPopular": "Advance Wars",
  "DuraciónEnElMercado": "1 año",
  "generation": "Sexta Generacion",
  "numberGeneration": 6,
  "numberType": 7
},
{
  "id": 23,
  "name": "Nintendo S. Lite",
  "description": "La consola se diseñó exclusivamente para su uso portátil, sin incluir un dock para acoplarla a la TV, resultando en un modelo más compacto. Fue diseñada por Nintendo para facilitar el transporte de su nueva generación de consolas. ",
  "imageUrl":
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Nintendo_Switch_Lite_representation.png/1280px-Nintendo_Switch_Lite_representation.png",

  "tipo": "Consola portátil",
  "PrecioDeLanzamiento": " $199.99 USD",
  "JuegoMásPopular": " Mario Kart 8 Deluxe",
  "DuraciónEnElMercado": "2019-Act.",
  "generation": "Séptima Generacion",
  "numberGeneration": 7,
  "numberType": 7,
},
{
  "id": 24,
  "name": "Nintendo Switch OLED",
  "description": "La nueva consola cuenta con una vibrante pantalla OLED de 7 pulgadas (17.78 cm), un soporte ajustable y amplio, una base con puerto LAN para conexión por cable, almacenamiento interno de 64 GB y audio mejorado.",
  "imageUrl":
      "/data/img/nintendo-switch-oled-.png",
  "tipo": "Consola híbrida",
  "PrecioDeLanzamiento": "  $349.99 USD",
  "JuegoMásPopular":"Mario Kart 8 Deluxe",
  "DuraciónEnElMercado": "2021-Act.",
  "generation": "Octava Generacion",
  "numberGeneration": 8,
  "numberType": 2,
},];

